name: 'Action to test fetch through merge-base'
author: Nils Homer (@nh13)
description: 'Action to test fetch through merge-base'
branding:
  icon: "code"
  color: "green"
inputs:
  base-ref:
    default: ${{ github.base_ref }}
    required: false
    description: >
      The base ref or target branch in the workflow run.  If empty or 
      not defined, the `fallback-base-ref` input ref will be used.
  head-ref:
    default: ${{ github.head_ref }}
    required: false
    description: >
      The head ref or source branch in the workflow run.  If empty or
      not defined, the `fallback-head-ref` input ref will be used.
  fallback-base-ref:
    default: "main"
    required: false
    description: >
      The base ref to use when `base-ref` is empty or not defined.  For
      example, when using `github.base_ref` for `base-ref`, and the
      workflow is not a `pull_request` or `pull_request_target`, then
      the `base-ref` is not defined, so this ref will be used.
  fallback-head-ref: 
    default: ${{ github.sha }}
    required: false
    description: >
      The head ref to use when `head-ref` is empty or not defined.  For
      example, when using `github.head_ref` for `head-ref`, and the
      workflow is not a `pull_request` or `pull_request_target`, then
      the `head-ref` is not defined, so this ref will be used.
  deepen-length:
    default: 10
    required: false
    description: >
      The number of commits to increase from the tip of each base and ref
      history when `git merge-base` fails to find the common ancestor of 
      the two commits.
  fail-after:
    default: 100
    required: false
    description: >
      The number of attempts to deepen before the action fails.
runs:
  using: "composite"
  steps: 
    - name: Checkout mock data
      uses: actions/checkout@v4
      with:
        repository: fulcrumgenomics/fetch-through-merge-base-mock
        path: __testing_dir__
        fetch-depth: 1
    - name: run the test
      id: the-test
      continue-on-error: true
      uses: ./
      with:
        base-ref: ${{ inputs.base-ref }}
        head-ref: ${{ inputs.head-ref }}
        fallback-base-ref: ${{ inputs.fallback-base-ref }}
        fallback-head-ref: ${{ inputs.fallback-head-ref }}
        deepen-length: ${{ inputs.deepen-length }}
        fail-after: ${{ inputs.fail-after }}
        working-directory: ./__testing_dir__
    - name: cleanup the testing directory
      shell: bash
      run: rm -rf __testing_dir__
    - name: Check failure
      shell: bash
      run: |
        if [[ ${{ steps.the-test.outcome }} == "failure" ]]; then
          echo "Test failed";
          exit 1;
        fi
